# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\x0f\x64rone.telemetry\"\xd9\x01\n\x10TelemetryMessage\x12\x10\n\x08\x64rone_id\x18\x01 \x01(\t\x12\x12\n\nmission_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12.\n\x08position\x18\x04 \x01(\x0b\x32\x1c.drone.telemetry.GpsPosition\x12-\n\x06status\x18\x05 \x01(\x0b\x32\x1d.drone.telemetry.FlightStatus\x12-\n\x07\x62\x61ttery\x18\x06 \x01(\x0b\x32\x1c.drone.telemetry.BatteryInfo\"v\n\x0bGpsPosition\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x03 \x01(\x01\x12\r\n\x05speed\x18\x04 \x01(\x02\x12\x0f\n\x07heading\x18\x05 \x01(\x02\x12\x10\n\x08\x61\x63\x63uracy\x18\x06 \x01(\x02\"\x8c\x01\n\x0c\x46lightStatus\x12*\n\x05state\x18\x01 \x01(\x0e\x32\x1b.drone.telemetry.DroneState\x12\r\n\x05pitch\x18\x02 \x01(\x02\x12\x0c\n\x04roll\x18\x03 \x01(\x02\x12\x0b\n\x03yaw\x18\x04 \x01(\x02\x12\x12\n\nwind_speed\x18\x05 \x01(\x02\x12\x12\n\nerror_code\x18\x06 \x01(\t\"_\n\x0b\x42\x61tteryInfo\x12\x12\n\npercentage\x18\x01 \x01(\x02\x12\x0f\n\x07voltage\x18\x02 \x01(\x02\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\x16\n\x0etime_remaining\x18\x04 \x01(\x05*t\n\nDroneState\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04IDLE\x10\x01\x12\x0e\n\nTAKING_OFF\x10\x02\x12\n\n\x06\x46LYING\x10\x03\x12\x0c\n\x08HOVERING\x10\x04\x12\x0b\n\x07LANDING\x10\x05\x12\r\n\tRETURNING\x10\x06\x12\t\n\x05\x45RROR\x10\x07\x42\x36Z4github.com/tu-usuario/drone-platform/proto/telemetryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/tu-usuario/drone-platform/proto/telemetry'
  _globals['_DRONESTATE']._serialized_start=616
  _globals['_DRONESTATE']._serialized_end=732
  _globals['_TELEMETRYMESSAGE']._serialized_start=37
  _globals['_TELEMETRYMESSAGE']._serialized_end=254
  _globals['_GPSPOSITION']._serialized_start=256
  _globals['_GPSPOSITION']._serialized_end=374
  _globals['_FLIGHTSTATUS']._serialized_start=377
  _globals['_FLIGHTSTATUS']._serialized_end=517
  _globals['_BATTERYINFO']._serialized_start=519
  _globals['_BATTERYINFO']._serialized_end=614
# @@protoc_insertion_point(module_scope)
